# -*- coding: utf-8 -*-
"""Procesamiento de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HJrru2XIMFeGFG2-81nJbOvURqYvMdyv
"""

!unzip OlistData.zip

import numpy as np
import pandas as pd
sellers = pd.read_csv('olist_sellers_dataset.csv')
sellers[:10]

customers = pd.read_csv('olist_customers_dataset.csv')
customers[:10]

geolocations = pd.read_csv("olist_geolocation_dataset.csv")
geolocations[:10]

items = pd.read_csv("olist_order_items_dataset.csv")
items[:10]

payments = pd.read_csv("olist_order_payments_dataset.csv")
payments[:10]

products = pd.read_csv("olist_products_dataset.csv")
products[:10]

reviews = pd.read_csv("olist_order_reviews_dataset.csv")
reviews[:10]

orders = pd.read_csv("olist_orders_dataset.csv")
orders[:10]

Final_data = pd.merge(orders, customers, on='customer_id', how='inner')
# To merge more dataframes, you would chain .merge() calls or perform them sequentially.
# Example for the next step, merging with reviews:
Final_data = pd.merge(Final_data, reviews, on='order_id', how='inner')
Final_data = pd.merge(Final_data, payments, on='order_id', how='inner')
Final_data = pd.merge(Final_data, items, on='order_id', how='inner')
Final_data = pd.merge(Final_data, products, on='product_id', how='inner')
Final_data = pd.merge(Final_data, sellers, on='seller_id', how='inner')
Final_data

Final_data.columns

len(Final_data["customer_id"].unique())

customer_purchase_data = Final_data[['customer_unique_id', 'order_purchase_timestamp']].copy()
customer_purchase_data['order_purchase_timestamp'] = pd.to_datetime(customer_purchase_data['order_purchase_timestamp'])
print(customer_purchase_data.head())
print(customer_purchase_data.info())

snapshot_date = customer_purchase_data['order_purchase_timestamp'].max() + pd.DateOffset(days=1)
print(f"Snapshot Date: {snapshot_date}")

last_purchase_date = customer_purchase_data.groupby('customer_unique_id')['order_purchase_timestamp'].max().reset_index()
last_purchase_date.columns = ['customer_unique_id', 'last_purchase_date']
print(last_purchase_date.head())

rfm_data = pd.DataFrame(last_purchase_date['customer_unique_id'])
rfm_data['Recency'] = (snapshot_date - last_purchase_date['last_purchase_date']).dt.days
print(rfm_data.head())

churn_threshold = 90  # Example: 90 days
rfm_data['churned'] = rfm_data['Recency'].apply(lambda x: 1 if x > churn_threshold else 0)
print(rfm_data.head())

print(rfm_data.head())
print(rfm_data.info())

frequency_df = Final_data.groupby('customer_unique_id')['order_id'].nunique().reset_index()
frequency_df.columns = ['customer_unique_id', 'Frequency']
print(frequency_df.head())

monetary_df = Final_data.groupby('customer_unique_id')['payment_value'].sum().reset_index()
monetary_df.columns = ['customer_unique_id', 'Monetary']
print(monetary_df.head())

rfm_data = pd.merge(rfm_data, frequency_df, on='customer_unique_id', how='left')
print(rfm_data.head())

rfm_data = pd.merge(rfm_data, monetary_df, on='customer_unique_id', how='left')
print(rfm_data.head())

print(rfm_data.head())
print(rfm_data.info())

rfm_data.to_csv('rfm_data.csv', index=False)

